### ISSUE TITLE
User settings and Add server overlap

### ISSUE THREAD

**Issue by Qbiczeq** [gabe7384/Ajern#2]
![FyE25](https://user-images.githubusercontent.com/48165482/94987118-127d4480-0564-11eb-99ae-2fc28ef3d31b.gif)

**Comment by Creationsss** [comment]
Ah I've been trying to fix this for a while no luck tho! Guess ill have to keep trying haha.

**Comment by giren7384** [comment]
I cant really say that is a bug or issue I guess because there's not much you could really change to not cause that, I would say just put more of your servers in folders.
